name 'jhoblitt-pureftpd'
version '1.2.0'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache + GPLv3'
project_page 'https://github.com/jhoblitt/puppet-pureftpd'
source 'https://github.com/jhoblitt/puppet-pureftpd.git'
summary 'Manages the pure-ftpd package with comprehensive configuration support'
description 'Manages the pure-ftpd package with comprehensive configuration support'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
