# == Class: pureftpd::config
#
# This module manages the pure-ftpd server configuration file
#
# === Parameters
#
# === Authors
#
# 5Ub-Z3r0
# Joshua Hoblitt <jhoblitt@cpan.org>
#

class pureftpd::config(
  $IPV4Only                   = undef,
  $IPV6Only                   = undef,
  $ChrootEveryone             = undef,
  $BrokenClientsCompatibility = undef,
  $Daemonize                  = undef,
  $VerboseLog                 = undef,
  $DisplayDotFiles            = undef,
  $AnonymousOnly              = undef,
  $NoAnonymous                = undef,
  $DontResolve                = undef,
  $AnonymousCanCreateDirs     = undef,
  $NATmode                    = undef,
  $CallUploadScript           = undef,
  $AntiWarez                  = undef,
  $AllowUserFXP               = undef,
  $AllowAnonymousFXP          = undef,
  $ProhibitDotFilesWrite      = undef,
  $ProhibitDotFilesRead       = undef,
  $AllowDotFiles              = undef,
  $AutoRename                 = undef,
  $AnonymousCantUpload        = undef,
  $LogPID                     = undef,
  $NoChmod                    = undef,
  $KeepAllFiles               = undef,
  $CreateHomeDir              = undef,
  $NoRename                   = undef,
  $CustomerProof              = undef,
  $NoTruncate                 = undef,
  $FileSystemCharset          = undef,
  $ClientCharset              = undef,
  $SyslogFacility             = undef,
  $FortunesFile               = undef,
  $ForcePassiveIP             = undef,
  $Bind                       = undef,
  $AnonymousBandwidth         = undef,
  $UserBandwidth              = undef,
  $TrustedIP                  = undef,
  $AltLog                     = undef,
  $PIDFile                    = undef,
  $MaxIdleTime                = undef,
  $MaxDiskUsage               = undef,
  $TrustedGID                 = undef,
  $MaxClientsNumber           = undef,
  $MaxClientsPerIP            = undef,
  $MaxLoad                    = undef,
  $MinUID                     = undef,
  $TLS                        = undef,
  $LimitRecursion             = undef,
  $PassivePortRange           = undef,
  $AnonymousRatio             = undef,
  $UserRatio                  = undef,
  $Umask                      = undef,
) inherits pureftpd::params {

  $conf_options = [
    'IPV4Only',
    'IPV6Only',
    'ChrootEveryone',
    'BrokenClientsCompatibility',
    'Daemonize',
    'VerboseLog',
    'DisplayDotFiles',
    'AnonymousOnly',
    'NoAnonymous',
    'DontResolve',
    'AnonymousCanCreateDirs',
    'NATmode',
    'CallUploadScript',
    'AntiWarez',
    'AllowUserFXP',
    'AllowAnonymousFXP',
    'ProhibitDotFilesWrite',
    'ProhibitDotFilesRead',
    'AllowDotFiles',
    'AutoRename',
    'AnonymousCantUpload',
    'LogPID',
    'NoChmod',
    'KeepAllFiles',
    'CreateHomeDir',
    'NoRename',
    'CustomerProof',
    'NoTruncate',
    'FileSystemCharset',
    'ClientCharset',
    'SyslogFacility',
    'FortunesFile',
    'ForcePassiveIP',
    'Bind',
    'AnonymousBandwidth',
    'UserBandwidth',
    'TrustedIP',
    'AltLog',
    'PIDFile',
    'MaxIdleTime',
    'MaxDiskUsage',
    'TrustedGID',
    'MaxClientsNumber',
    'MaxClientsPerIP',
    'MaxLoad',
    'MinUID',
    'TLS',
    'LimitRecursion',
    'PassivePortRange',
    'AnonymousRatio',
    'UserRatio',
    'Umask',
    'Quota',
    'PerUserLimits',
    'LDAPConfigFile',
    'MySQLConfigFile',
    'PGSQLConfigFile',
    'PureDB',
    'ExtAuth',
  ]

  file { $pureftpd::params::conf_path:
    ensure  => file,
    content => template("${module_name}/${pureftpd::params::conf_erb}"),
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    notify  => Service[$pureftpd::params::service_name]
  }
}
